### ISSUE TITLE
stripBom.stream is not a function

### ISSUE THREAD

**Issue by rxalfred** [twolfson/gulp.spritesmith#138] opened 2018-02-09 03:05 UTC
C:\Users\source\repos\SinglePageApplicationCoreSample\SinglePageApplicationCoreSample\node_modules\vinyl-fs\lib\src\getContents\streamFile.js:8
    .pipe(stripBom.stream());
                   ^
TypeError: stripBom.stream is not a function
    at streamFile (C:\Users\source\repos\SinglePageApplicationCoreSample\SinglePageApplicationCoreSample\node_modules\vinyl-fs\lib\src\getContents\streamFile.js:8:20)
    at WriteStream.<anonymous> (C:\Users\\source\repos\SinglePageApplicationCoreSample\SinglePageApplicationCoreSample\node_modules\vinyl-fs\lib\dest\writeContents\writeStream.js:16:5)
    at WriteStream.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at WriteStream.emit (events.js:166:7)
    at finishMaybe (_stream_writable.js:468:14)
    at afterWrite (_stream_writable.js:347:3)
    at onwrite (_stream_writable.js:337:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fs.js:1990:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:1957:5)
Process terminated with code 1.

**Comment by twolfson** [comment] 2018-02-09 03:14
This looks like a dependency resolution issue. Your `gulp` is using `vinyl-fs@1.x.x` and `strip-dom@latest` doesn't seem to have a `stripBom.stream` method. Try the following:

```bash
# Wipe and re-install node modules
rm -r node_modules
npm install
```

If that doesn't fix the issue, then I'll need to know your version of `node`, `npm`, `gulp`, `vinyl-fs`, `gulp.spritesmith`, and `strip-bom` (though this is unrelated to the issue)

Closing eagerly as I think wiping/reinstalling `node_modules` should resolve the issue

**Closed by twolfson** 2018-02-09 03:14 UTC

**Comment by rxalfred** [comment] 2018-02-09 03:29
vinyl-fs version 3.0.2

**Comment by twolfson** [comment] 2018-02-09 03:31
Did you read that after you reinstall the `node_modules`? If so, then the issue is probably fixed

`vinyl-fs@3.0.2` doesn't have the file `lib/src/getContents/streamFile.js` referenced in the stack trace:

https://github.com/gulpjs/vinyl-fs/tree/v3.0.2/lib/src

**Comment by twolfson** [comment] 2018-02-09 03:34
Is the error message exactly the same as the one you pasted? And how did you resolve the package versions? `npm ls`?

**Comment by rxalfred** [comment] 2018-02-09 04:11
It is working now.. due to the old version of vinyl-fs used in local project.
thanks @twolfson  for your help (Y)

**Comment by twolfson** [comment] 2018-02-09 04:14
Great! Glad to hear everything is fixed =)
