### ISSUE TITLE
[Feature Request]generate sprite image with md5 file name  to prevent browser cache

### ISSUE THREAD

**Issue by TangMonk** [twolfson/gulp.spritesmith#146] opened 2019-09-05 07:04 UTC

**Comment by twolfson** [comment] 2019-09-07 22:23
We recommend using other `gulp` plugins to generate `md5` filenames. This issue is a duplicate of https://github.com/twolfson/gulp.spritesmith/issues/26

I don't have any up to date plugin names but believe there should be something out there for this

**Closed by twolfson** 2019-09-07 22:23 UTC
