### ISSUE TITLE
auto add 'icon-' prefix?

### ISSUE THREAD

**Issue by GerryLon** [twolfson/gulp.spritesmith#133] opened 2017-11-17 11:14 UTC
my filename is 'icon-alert.png',
but generated class name is 'icon-icon-alert',
how to remove prefix 'icon-'?

my gulpfile.js is:
```js
var gulp = require('gulp');
var spritesmith = require('gulp.spritesmith');

gulp.task('sprite', function () {
  var spriteData = gulp.src('src/img/slice/*.png').pipe(spritesmith({
    imgName: 'img/sprite.png',
    cssName: 'css/sprite.less',
    padding: 5,
    cssFormat: 'css', // less文件内容以css的格式输出
  	cssVarMap: function (sprite) {
                // here is ok, output is 'icon-alert'
               // why generated class name is added 'icon-' prefix?
		console.log('-----------:', sprite.name);
	},

  }));
  return spriteData.pipe(gulp.dest('dist'));
});
```

**Comment by twolfson** [comment] 2017-11-17 18:58
This is a duplicate of #110. Please see it for documentation on resolving the issue

**Closed by twolfson** 2017-11-17 18:58 UTC
